### ISSUE TITLE
CloneVM_Task Fail

### ISSUE THREAD

**Issue by shhgs** [xuru/pyvisdk#4]
Hi Eric:

I am using pyvisdk and I got this error while cloning and VM.

The code looks like that::

```
def createvm(buildreq):
    relocSpec = VirtualMachineRelocateSpec( conn
                                          , datastore = ds_depesx1.ref
                                          , host = esx_depesx1.ref
                                          , pool = esx_depesx1.parent.ref)
    cloneSpec = VirtualMachineCloneSpec( conn
                                       , location = relocSpec
                                       , powerOn = False
                                       , template = False)
    tmpl_vmbuild.CloneVM_Task(getFolder(buildreq), buildreq.hostname, cloneSpec)
```

..

And the error messages looks like this::

```
$ python createvm.py
[2012-03-01 11:23:57,333][INFO    ] vim.login:41 Successfully logged into https://vcenter.fqdn/sdk
[2012-03-01 11:24:02,311][ERROR   ] client.send:648 <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="urn:vim25" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:CloneVM_Task>
         <ns0:_this type="VirtualMachine">vm-739</ns0:_this>
         <ns0:folder type="Folder">group-v10255</ns0:folder>
         <ns0:name>cdcchinarch1.cdc</ns0:name>
         <ns0:spec>
            <ns0:location>
               <ns0:datastore type="Datastore">datastore-6143</ns0:datastore>
               <ns0:pool type="ClusterComputeResource">domain-c565</ns0:pool>
               <ns0:host type="HostSystem">host-6140</ns0:host>
               <ns0:transform/>
            </ns0:location>
            <ns0:template>false</ns0:template>
            <ns0:powerOn>false</ns0:powerOn>
            <ns0:snapshot/>
         </ns0:spec>
      </ns0:CloneVM_Task>
   </ns1:Body>
</SOAP-ENV:Envelope>
Traceback (most recent call last):
  File "createvm.py", line 89, in <module>
    createvm(req)
  File "createvm.py", line 84, in createvm
    tmpl_vmbuild.CloneVM_Task(getFolder(buildreq), buildreq.hostname, cloneSpec)
  File "/home/shhgs/.local/lib/python2.7/site-packages/pyvisdk-0.9dev_20120228-py2.7.egg/pyvisdk/mo/virtual_machine.py", line 200, in CloneVM_Task
    return self.delegate("CloneVM_Task")(folder, name, spec)
  File "/home/shhgs/.local/lib/python2.7/site-packages/pyvisdk-0.9dev_20120228-py2.7.egg/pyvisdk/base/base_entity.py", line 46, in __call__
    rv = self.__target(*args, **kwargs)
  File "/home/shhgs/.local/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/home/shhgs/.local/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/home/shhgs/.local/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File "/home/shhgs/.local/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/client.py", line 702, in failed
    r, p = binding.get_fault(reply)
  File "/home/shhgs/.local/lib/python2.7/site-packages/suds-0.4-py2.7.egg/suds/bindings/binding.py", line 265, in get_fault
    raise WebFault(p, faultroot)
suds.WebFault: Server raised fault: 'Invalid argument'
```

..

I don't know much about the VMware SDK, so can you please help troubleshooting this problem?

Thanks
- shhgs

**Comment by xuru** [comment]
Unfortunately I don't have access to an esx server anymore.  If you know of a way that I could get access to one, I'd be happy to have a look...  I'll have to look and see if 4.1 is free now that 5 is out...
